In [1]:
import dask.dataframe as dd
dtypes_dict = {
    'game_num': 'int8', 'event_id': 'int8', 'event_time': 'float16',
    'ball_pos_x': 'float16', 'ball_pos_y': 'float16', 'ball_pos_z': 'float16',
    'ball_vel_x': 'float16', 'ball_vel_y': 'float16', 'ball_vel_z': 'float16',
    'p0_pos_x': 'float16', 'p0_pos_y': 'float16', 'p0_pos_z': 'float16',
    'p0_vel_x': 'float16', 'p0_vel_y': 'float16', 'p0_vel_z': 'float16',
    'p0_boost': 'float16', 'p1_pos_x': 'float16', 'p1_pos_y': 'float16',
    'p1_pos_z': 'float16', 'p1_vel_x': 'float16', 'p1_vel_y': 'float16',
    'p1_vel_z': 'float16', 'p1_boost': 'float16', 'p2_pos_x': 'float16',
    'p2_pos_y': 'float16', 'p2_pos_z': 'float16', 'p2_vel_x': 'float16',
    'p2_vel_y': 'float16', 'p2_vel_z': 'float16', 'p2_boost': 'float16',
    'p3_pos_x': 'float16', 'p3_pos_y': 'float16', 'p3_pos_z': 'float16',
    'p3_vel_x': 'float16', 'p3_vel_y': 'float16', 'p3_vel_z': 'float16',
    'p3_boost': 'float16', 'p4_pos_x': 'float16', 'p4_pos_y': 'float16',
    'p4_pos_z': 'float16', 'p4_vel_x': 'float16', 'p4_vel_y': 'float16',
    'p4_vel_z': 'float16', 'p4_boost': 'float16', 'p5_pos_x': 'float16',
    'p5_pos_y': 'float16', 'p5_pos_z': 'float16', 'p5_vel_x': 'float16',
    'p5_vel_y': 'float16', 'p5_vel_z': 'float16', 'p5_boost': 'float16',
    'boost0_timer': 'float16', 'boost1_timer': 'float16', 'boost2_timer': 'float16',
    'boost3_timer': 'float16', 'boost4_timer': 'float16', 'boost5_timer': 'float16',
    'player_scoring_next': 'O', 'team_scoring_next': 'O', 'team_A_scoring_within_10sec': 'int8',
    'team_B_scoring_within_10sec': 'int8'
}


df = dd.read_csv('./data/train_*.csv', dtype = dtypes_dict)

In [2]:
from datetime import datetime
start = datetime.now()

df = dd.read_csv('./data/train_*.csv', dtype = dtypes_dict)
df = df.compute()

end = datetime.now()
time_readcsv = end - start
print(f'Time taken for reading data: {time_readcsv.seconds} seconds')

Time taken for reading data: 7 seconds

In [3]:
df.keys()

Index(['game_num', 'event_id', 'event_time', 'ball_pos_x', 'ball_pos_y',
       'ball_pos_z', 'ball_vel_x', 'ball_vel_y', 'ball_vel_z', 'p0_pos_x',
       'p0_pos_y', 'p0_pos_z', 'p0_vel_x', 'p0_vel_y', 'p0_vel_z', 'p0_boost',
       'p1_pos_x', 'p1_pos_y', 'p1_pos_z', 'p1_vel_x', 'p1_vel_y', 'p1_vel_z',
       'p1_boost', 'p2_pos_x', 'p2_pos_y', 'p2_pos_z', 'p2_vel_x', 'p2_vel_y',
       'p2_vel_z', 'p2_boost', 'p3_pos_x', 'p3_pos_y', 'p3_pos_z', 'p3_vel_x',
       'p3_vel_y', 'p3_vel_z', 'p3_boost', 'p4_pos_x', 'p4_pos_y', 'p4_pos_z',
       'p4_vel_x', 'p4_vel_y', 'p4_vel_z', 'p4_boost', 'p5_pos_x', 'p5_pos_y',
       'p5_pos_z', 'p5_vel_x', 'p5_vel_y', 'p5_vel_z', 'p5_boost',
       'boost0_timer', 'boost1_timer', 'boost2_timer', 'boost3_timer',
       'boost4_timer', 'boost5_timer', 'player_scoring_next',
       'team_scoring_next', 'team_A_scoring_within_10sec',
       'team_B_scoring_within_10sec'],
      dtype='object')

In [4]:
df.shape

(4318155, 61)

In [6]:
df.head(5)

,game_num,event_id,event_time,ball_pos_x,ball_pos_y,ball_pos_z,ball_vel_x,ball_vel_y,ball_vel_z,p0_pos_x,...,boost0_timer,boost1_timer,boost2_timer,boost3_timer,boost4_timer,boost5_timer,player_scoring_next,team_scoring_next,team_A_scoring_within_10sec,team_B_scoring_within_10sec
0,1,-22,-33.31250,-0.0,0.0,1.854492,-0.0,0.0,0.0,41.81250,...,0.0,0.0,0.0,0.0,0.0,0.0,3,B,0,0
1,1,-22,-33.21875,-0.0,0.0,1.854492,-0.0,0.0,0.0,42.25000,...,0.0,0.0,0.0,0.0,0.0,0.0,3,B,0,0
2,1,-22,-33.09375,-0.0,0.0,1.854492,-0.0,0.0,0.0,43.21875,...,0.0,0.0,0.0,0.0,0.0,0.0,3,B,0,0
3,1,-22,-33.00000,-0.0,0.0,1.854492,-0.0,0.0,0.0,43.90625,...,0.0,0.0,0.0,0.0,0.0,0.0,3,B,0,0
4,1,-22,-32.87500,-0.0,0.0,1.854492,-0.0,0.0,0.0,44.96875,...,0.0,0.0,0.0,0.0,0.0,0.0,3,B,0,0

In [19]:
# Viendo jugadores desaparecidos o muertos
for i in df.keys():
    print(f"{i}: " + str(df[i].isnull().sum()))

game_num: 0
event_id: 0
event_time: 0
ball_pos_x: 0
ball_pos_y: 0
ball_pos_z: 0
ball_vel_x: 0
ball_vel_y: 0
ball_vel_z: 0
p0_pos_x: 39631
p0_pos_y: 39631
p0_pos_z: 39631
p0_vel_x: 39631
p0_vel_y: 39631
p0_vel_z: 39631
p0_boost: 39631
p1_pos_x: 38558
p1_pos_y: 38558
p1_pos_z: 38558
p1_vel_x: 38558
p1_vel_y: 38558
p1_vel_z: 38558
p1_boost: 38558
p2_pos_x: 38635
p2_pos_y: 38635
p2_pos_z: 38635
p2_vel_x: 38635
p2_vel_y: 38635
p2_vel_z: 38635
p2_boost: 38635
p3_pos_x: 39252
p3_pos_y: 39252
p3_pos_z: 39252
p3_vel_x: 39252
p3_vel_y: 39252
p3_vel_z: 39252
p3_boost: 39252
p4_pos_x: 38576
p4_pos_y: 38576
p4_pos_z: 38576
p4_vel_x: 38576
p4_vel_y: 38576
p4_vel_z: 38576
p4_boost: 38576
p5_pos_x: 39431
p5_pos_y: 39431
p5_pos_z: 39431
p5_vel_x: 39431
p5_vel_y: 39431
p5_vel_z: 39431
p5_boost: 39431
boost0_timer: 0
boost1_timer: 0
boost2_timer: 0
boost3_timer: 0
boost4_timer: 0
boost5_timer: 0
player_scoring_next: 0
team_scoring_next: 1017750
team_A_scoring_within_10sec: 0
team_B_scoring_within_10sec: 0

In [23]:
# Porcentaje de instantes donde hay muertos
38558/4318155 *100

0.8929276508138314

## Eliminando columnas no Ãºtiles

In [24]:
import gc
gc.collect()
from lightgbm import LGBMClassifier
#df.dropna(inplace = True)
y_b = df['team_B_scoring_within_10sec']
y_a = df['team_A_scoring_within_10sec']
to_drop = ['game_num','event_id', 'event_time', 'player_scoring_next',
       'team_scoring_next',
       'team_B_scoring_within_10sec','team_A_scoring_within_10sec']
df.drop(to_drop, inplace = True, axis = 1)

In [26]:
df.keys()

Index(['ball_pos_x', 'ball_pos_y', 'ball_pos_z', 'ball_vel_x', 'ball_vel_y',
       'ball_vel_z', 'p0_pos_x', 'p0_pos_y', 'p0_pos_z', 'p0_vel_x',
       'p0_vel_y', 'p0_vel_z', 'p0_boost', 'p1_pos_x', 'p1_pos_y', 'p1_pos_z',
       'p1_vel_x', 'p1_vel_y', 'p1_vel_z', 'p1_boost', 'p2_pos_x', 'p2_pos_y',
       'p2_pos_z', 'p2_vel_x', 'p2_vel_y', 'p2_vel_z', 'p2_boost', 'p3_pos_x',
       'p3_pos_y', 'p3_pos_z', 'p3_vel_x', 'p3_vel_y', 'p3_vel_z', 'p3_boost',
       'p4_pos_x', 'p4_pos_y', 'p4_pos_z', 'p4_vel_x', 'p4_vel_y', 'p4_vel_z',
       'p4_boost', 'p5_pos_x', 'p5_pos_y', 'p5_pos_z', 'p5_vel_x', 'p5_vel_y',
       'p5_vel_z', 'p5_boost', 'boost0_timer', 'boost1_timer', 'boost2_timer',
       'boost3_timer', 'boost4_timer', 'boost5_timer'],
      dtype='object')

In [31]:
df['p0_norm']=(df['p0_pos_x']**2+df['p0_pos_y']**2+df['p0_pos_z']**2 )**.5
df['p1_norm']=(df['p1_pos_x']**2+df['p1_pos_y']**2+df['p1_pos_z']**2 )**.5
df['p2_norm']=(df['p2_pos_x']**2+df['p2_pos_y']**2+df['p2_pos_z']**2 )**.5
df['p3_norm']=(df['p3_pos_x']**2+df['p3_pos_y']**2+df['p3_pos_z']**2 )**.5
df['p4_norm']=(df['p4_pos_x']**2+df['p4_pos_y']**2+df['p4_pos_z']**2 )**.5
df['p5_norm']=(df['p5_pos_x']**2+df['p5_pos_y']**2+df['p5_pos_z']**2 )**.5

In [33]:
df['p0_norm'].isna().sum()

39631

In [34]:
df['p0_off'] = 1-df.loc[:,['p0_norm']].count(axis=1)
df['p1_off'] = 1-df.loc[:,['p1_norm']].count(axis=1)
df['p2_off'] = 1-df.loc[:,['p2_norm']].count(axis=1)
df['p3_off'] = 1-df.loc[:,['p3_norm']].count(axis=1)
df['p4_off'] = 1-df.loc[:,['p4_norm']].count(axis=1)
df['p5_off'] = 1-df.loc[:,['p5_norm']].count(axis=1)

In [37]:
df['teamA_off']=df['p0_off']+df['p1_off']+df['p2_off'] 
df['teamB_off']=df['p3_off']+df['p4_off']+df['p5_off']
df

,ball_pos_x,ball_pos_y,ball_pos_z,ball_vel_x,ball_vel_y,ball_vel_z,p0_pos_x,p0_pos_y,p0_pos_z,p0_vel_x,...,p4_norm,p5_norm,p0_off,p1_off,p2_off,p3_off,p4_off,p5_off,teamA_off,teamB_off
0,-0.000000,0.0000,1.854492,-0.00000,0.000000,0.000000,41.81250,-51.937500,0.340088,5.636719,...,66.6875,63.71875,0,0,0,0,0,0,0,0
1,-0.000000,0.0000,1.854492,-0.00000,0.000000,0.000000,42.25000,-52.437500,0.340088,5.289062,...,67.5625,62.28125,0,0,0,0,0,0,0,0
2,-0.000000,0.0000,1.854492,-0.00000,0.000000,0.000000,43.21875,-54.062500,1.146484,5.687500,...,69.6250,59.43750,0,0,0,0,0,0,0,0
3,-0.000000,0.0000,1.854492,-0.00000,0.000000,0.000000,43.90625,-55.218750,1.593750,10.593750,...,71.4375,57.03125,0,0,0,0,0,0,0,0
4,-0.000000,0.0000,1.854492,-0.00000,0.000000,0.000000,44.96875,-57.093750,2.072266,10.632812,...,73.4375,54.00000,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16973,-9.273438,91.1250,4.472656,47.56250,33.906250,-5.851562,-66.12500,42.375000,1.865234,-7.648438,...,104.5625,61.37500,0,0,0,0,0,0,0,0
16974,-5.316406,94.0000,3.935547,47.43750,33.812500,-6.917969,-67.43750,35.968750,2.257812,-7.296875,...,104.2500,56.84375,0,0,0,0,0,0,0,0
16975,0.208984,97.9375,3.035156,47.28125,33.687500,-8.406250,-68.00000,32.906250,2.333984,-7.296875,...,104.0000,54.68750,0,0,0,0,0,0,0,0
16976,3.750000,100.4375,2.365234,47.15625,33.625000,-9.359375,-68.68750,29.562500,2.324219,-7.296875,...,103.7500,52.37500,0,0,0,0,0,0,0,0
16977,8.992188,104.1250,2.152344,42.68750,29.796875,5.398438,-69.43750,25.921875,2.289062,-7.300781,...,103.5625,50.53125,0,0,0,0,0,0,0,0

In [52]:
to_drop = ['p0_off','p1_off', 'p2_off', 'p3_off',
       'p4_off', 'p5_off']
df.drop(to_drop, inplace = True, axis = 1)
df

KeyError: "['p0_off' 'p1_off' 'p2_off' 'p3_off' 'p4_off' 'p5_off'] not found in axis"

In [43]:
#Train
model = LGBMClassifier()
model.fit(df, y_a)
print('Model A trained')

Model A trained

In [47]:
#Test -> hacer data feautirng de psociiones, , crear funcion que haga 
import pandas as pd
df2 = pd.read_csv('./data/test.csv')
df2.drop('id', axis = 1, inplace = True)

In [48]:
#data featuring sobre test
df2

,ball_pos_x,ball_pos_y,ball_pos_z,ball_vel_x,ball_vel_y,ball_vel_z,p0_pos_x,p0_pos_y,p0_pos_z,p0_vel_x,...,p5_vel_x,p5_vel_y,p5_vel_z,p5_boost,boost0_timer,boost1_timer,boost2_timer,boost3_timer,boost4_timer,boost5_timer
0,-56.270800,29.510000,17.348600,24.4994,-1.3114,11.006801,-35.776200,73.136800,1.2480,18.3870,...,3.948400,-16.710800,0.0074,71.000,0.0000,-3.2640,-6.1330,-6.8750,-7.0160,-3.230
1,2.852800,70.196000,8.949000,-8.1522,-65.5772,18.536400,22.926000,87.543800,0.3396,-41.9548,...,-15.496800,-14.876600,0.0050,66.700,0.0000,-1.6150,-5.9700,-5.5040,0.0000,-6.510
2,52.366400,-98.036800,14.249001,-2.0000,-45.2914,-15.423400,51.288998,-102.055595,6.3570,8.6380,...,0.905800,-27.413600,0.0042,80.400,-0.0316,0.0000,0.0000,-3.1290,0.0000,-3.678
3,36.365402,53.961403,23.161798,24.8294,-10.3286,-0.918000,16.424799,0.932800,0.3402,39.6276,...,-5.053200,-15.106999,0.0052,96.060,-6.4300,-4.0900,-7.8320,-5.7600,0.0000,-3.924
4,-23.262400,-53.391003,21.209600,-1.6676,-24.7788,3.481200,-19.681800,-93.913605,4.7832,-4.1376,...,22.200000,24.928001,0.0042,0.000,-9.8800,0.0000,-0.4456,-0.4915,-7.8300,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701138,-4.403200,97.837200,1.947000,-17.1874,5.8004,-0.919400,36.585200,45.023000,1.5646,-40.1184,...,-8.230801,-10.698600,-5.4644,0.392,0.0000,0.0000,0.0000,-3.5210,0.0000,-7.840
701139,-74.574600,-62.989000,5.712600,15.2064,-21.4224,0.637800,-81.560600,-48.214000,15.5750,0.2120,...,-5.291400,-15.463000,6.6894,0.000,-4.2700,0.0000,-7.9650,0.0000,0.0000,0.000
701140,-42.743397,-52.765602,4.220400,8.8498,32.8534,17.899399,10.959001,-39.320602,1.9344,35.9532,...,16.518800,-31.844599,0.0046,100.000,0.0000,-7.6250,-9.9300,0.0000,0.0000,0.000
701141,18.133001,-98.273796,32.703400,-5.7884,-60.7226,-5.504600,30.581999,13.514000,0.3402,-19.3438,...,7.217400,-26.050600,0.0054,91.750,0.0000,-0.1617,0.0000,-2.1520,-0.3772,-2.004
701142,-34.791000,-99.900600,5.260600,-23.6674,20.8914,6.089200,-31.181002,-90.865590,0.3398,-27.6896,...,-11.339800,-34.435802,-1.4792,20.620,-9.0160,-9.3500,-0.7666,-4.5500,0.0000,-5.184

In [49]:
df2['p0_norm']=(df2['p0_pos_x']**2+df2['p0_pos_y']**2+df2['p0_pos_z']**2 )**.5
df2['p1_norm']=(df2['p1_pos_x']**2+df2['p1_pos_y']**2+df2['p1_pos_z']**2 )**.5
df2['p2_norm']=(df2['p2_pos_x']**2+df2['p2_pos_y']**2+df2['p2_pos_z']**2 )**.5
df2['p3_norm']=(df2['p3_pos_x']**2+df2['p3_pos_y']**2+df2['p3_pos_z']**2 )**.5
df2['p4_norm']=(df2['p4_pos_x']**2+df2['p4_pos_y']**2+df2['p4_pos_z']**2 )**.5
df2['p5_norm']=(df2['p5_pos_x']**2+df2['p5_pos_y']**2+df2['p5_pos_z']**2 )**.5

In [50]:
df2['p0_off'] = 1-df2.loc[:,['p0_norm']].count(axis=1)
df2['p1_off'] = 1-df2.loc[:,['p1_norm']].count(axis=1)
df2['p2_off'] = 1-df2.loc[:,['p2_norm']].count(axis=1)
df2['p3_off'] = 1-df2.loc[:,['p3_norm']].count(axis=1)
df2['p4_off'] = 1-df2.loc[:,['p4_norm']].count(axis=1)
df2['p5_off'] = 1-df2.loc[:,['p5_norm']].count(axis=1)

In [51]:
df2['teamA_off']=df2['p0_off']+df2['p1_off']+df2['p2_off'] 
df2['teamB_off']=df2['p3_off']+df2['p4_off']+df2['p5_off']

In [53]:
to_drop = ['p0_off','p1_off', 'p2_off', 'p3_off',
       'p4_off', 'p5_off']
df2.drop(to_drop, inplace = True, axis = 1)
df2

,ball_pos_x,ball_pos_y,ball_pos_z,ball_vel_x,ball_vel_y,ball_vel_z,p0_pos_x,p0_pos_y,p0_pos_z,p0_vel_x,...,boost4_timer,boost5_timer,p0_norm,p1_norm,p2_norm,p3_norm,p4_norm,p5_norm,teamA_off,teamB_off
0,-56.270800,29.510000,17.348600,24.4994,-1.3114,11.006801,-35.776200,73.136800,1.2480,18.3870,...,-7.0160,-3.230,81.427793,79.263138,40.978057,94.038780,108.317061,74.748355,0,0
1,2.852800,70.196000,8.949000,-8.1522,-65.5772,18.536400,22.926000,87.543800,0.3396,-41.9548,...,0.0000,-6.510,90.496595,59.898443,70.639597,NaN,87.840006,100.725522,0,1
2,52.366400,-98.036800,14.249001,-2.0000,-45.2914,-15.423400,51.288998,-102.055595,6.3570,8.6380,...,0.0000,-3.678,114.395442,44.787874,107.277034,53.929095,108.038041,42.258564,0,0
3,36.365402,53.961403,23.161798,24.8294,-10.3286,-0.918000,16.424799,0.932800,0.3402,39.6276,...,0.0000,-3.924,16.454783,56.723254,85.082827,94.647321,57.236043,94.734147,0,0
4,-23.262400,-53.391003,21.209600,-1.6676,-24.7788,3.481200,-19.681800,-93.913605,4.7832,-4.1376,...,-7.8300,0.000,96.072980,46.493610,101.969829,38.167577,47.328074,65.623837,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701138,-4.403200,97.837200,1.947000,-17.1874,5.8004,-0.919400,36.585200,45.023000,1.5646,-40.1184,...,0.0000,-7.840,58.034433,100.051365,82.584269,100.623068,111.610639,87.287138,0,0
701139,-74.574600,-62.989000,5.712600,15.2064,-21.4224,0.637800,-81.560600,-48.214000,15.5750,0.2120,...,0.0000,0.000,96.017196,55.027016,97.062918,49.801845,74.648819,97.247853,0,0
701140,-42.743397,-52.765602,4.220400,8.8498,32.8534,17.899399,10.959001,-39.320602,1.9344,35.9532,...,0.0000,0.000,40.865038,45.098036,70.955663,106.085542,38.675339,72.606767,0,0
701141,18.133001,-98.273796,32.703400,-5.7884,-60.7226,-5.504600,30.581999,13.514000,0.3402,-19.3438,...,-0.3772,-2.004,33.436546,118.362530,98.054395,62.100910,73.615794,21.290690,0,0
701142,-34.791000,-99.900600,5.260600,-23.6674,20.8914,6.089200,-31.181002,-90.865590,0.3398,-27.6896,...,0.0000,-5.184,96.067298,105.688399,116.336767,76.856053,46.527837,47.468425,0,0

In [54]:
y_a_pred = model.predict_proba(df2)
del model
gc.collect()

397

In [55]:
model = LGBMClassifier()
model.fit(df, y_b)
print('Model B trained')
y_b_pred = model.predict_proba(df2)

submission = pd.read_csv('sample_submission.csv', usecols = ['id'])
submission['team_A_scoring_within_10sec'] = y_a_pred[:,1]
submission['team_B_scoring_within_10sec'] = y_b_pred[:,1]
submission.to_csv('submission.csv', index = False)

print('Submission saved')

Model B trained
Submission saved